name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'  # Explicitly specify Node.js version

    - name: Install dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y g++

    - name: Build Release (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p build/release
        g++ -o build/release/Gobblet-Gobblers src/*.cpp -O3
      shell: bash

    - name: Build Release (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir -p build/release
        g++ -o build/release/Gobblet-Gobblers.exe src/*.cpp -O3
      shell: pwsh

    - name: Upload Release Binaries (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Gobblet-Gobblers-linux
        path: build/release/Gobblet-Gobblers

    - name: Upload Release Binaries (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Gobblet-Gobblers-windows
        path: build/release/Gobblet-Gobblers.exe
